### ISSUE TITLE
Add branch protection rules and other important parameters

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-studio#10]
Things to check and add:

```[tasklist]
### Tasks
- [x] Add Branch protection rules
- [x] Any Github secrets needed to configure Docker builds
- [x] Add develop branch and set that as the default branch
```

Please feel free to add anything to the task list as well that I might have missed.

**Comment by navarroc** [comment]
Most of this is done, but I'm leaving this open since I cannot add the "checks" to the branch ruleset until we have actions. Checks (e.g. does it build) can't be set until we have an action that builds. I've created a basic ruleset so far and will update and close this issue when I can set those. Develop is also created now and unless there are repo specific secrets needed, everything is ready.
