### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-studio#2]
Add Github actions for:

```[tasklist]
### Tasks
- [ ] Add Docker build similar to IN-CORE UI
- [ ] Add linting checks.
- [ ] Also add a good readme
- [ ] (add other things that I might have missed)
```

**Comment by itsarijitray** [comment]
Can give it a shot? @Rashmil-1999
