### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-studio#3]
The goal is to set up authentication system as IN-CORE UI with keylcoak.

This involves:

```[tasklist]
### Tasks
- [x] Add Login page (keycloak login redirect)
- [x] Protect all routes with auth token, be sure to use a different cookie name from IN-CORE UI and Playbook (suggestion: incore-studio-auth-cookie)
- [x] Creating navbar and add  logout login options. It seems there will be "Dashboard" and "Logout" in the dropdown after logging in for now.
```
