### ISSUE TITLE
Improve "Add from Service" Dialog

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-studio#66]
We need to improve the look of the Dialog and aff certain features to it.

```[tasklist]
### Tasks
- [x] Add search bar to search via name and id. (preferably show only datasets related to the region selected in the project)
- [x] each result should display in a list of accordians with name being similar to incore UI viewers.
- [x] Upon clicking an entry, show short version of metadata and a button to select this dataset which will enable add to project button.
```
